In [4]:
from sklearn.decomposition import TruncatedSVD
from sklearn.preprocessing import Normalizer
import numpy as np
from sklearn.pipeline import Pipeline

from sklearn.cluster import KMeans
from sklearn.preprocessing import Normalizer

import csv
import pandas as pd
from sklearn.cross_validation import train_test_split
from collections import Counter
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import SGDClassifier
import numpy as np
import glob

In [2]:
train_file = csv.reader(open('train.data'), delimiter='\t')
next(train_file)
train_set = [x for x in train_file]

train_data, train_label = [line[2] for line in train_set], [line[1] for line in train_set]
from sklearn.cross_validation import train_test_split

x_train, x_validate, y_train, y_validate = train_test_split(train_data, train_label, test_size=0.2, random_state=0)

In [5]:
pipeline = Pipeline([
    ('vect', CountVectorizer(stop_words ='english', max_features=5000)),
    ('tfidf', TfidfTransformer()),
    ('svd', TruncatedSVD(n_components=5)),
    ('norm', Normalizer() ),
    ('clust', KMeans(n_clusters=5))
])

pipeline.fit(x_train)


/Users/nkozlovskaya/anaconda2/lib/python2.7/site-packages/sklearn/feature_extraction/text.py:1089: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if hasattr(X, 'dtype') and np.issubdtype(X.dtype, np.float):


Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=5000, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words='english',
     ...5, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0))])

In [7]:
clust_labels = pipeline.named_steps['clust'].labels_

In [8]:
clust_labels[:20]

array([0, 4, 1, 1, 0, 1, 3, 0, 0, 3, 1, 3, 3, 2, 2, 4, 1, 0, 3, 1],
      dtype=int32)

In [9]:
(np.array(map(int, y_train))-1)[:20]

array([2, 0, 1, 2, 4, 0, 4, 2, 3, 4, 3, 4, 3, 3, 2, 2, 4, 4, 2, 3])

In [15]:
labels = np.array(map(float, y_train))-1

# print("Homogeneity:", homogeneity_score(labels, clust_labels))
# print("Completeness:", completeness_score(labels, clust_labels))
# print("V-measure",  v_measure_score(labels, clust_labels))
# print("Adjusted Rand-Index:",  adjusted_rand_score(labels, clust_labels))

В чем проблема, если мы просто сейчас посмотрим на accuracy?

In [ ]:
# проблема в том, что метки могут быть перемешаны

In [49]:
code_dict = dict(zip(range(1, 6), [_1, _2, _3, _4, _5]))

In [50]:
code_dict

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}

In [47]:
clust_labels

array([0, 4, 1, ..., 0, 2, 3], dtype=int32)

In [51]:
 np.array(map(lambda x: code_dict[x], clust_labels+1))

array([1, 5, 2, ..., 1, 3, 4])

In [43]:
y_train = np.array(map(int, y_train))

In [52]:
import itertools
for _1, _2, _3, _4, _5 in itertools.permutations([1, 2, 3, 4, 5], 5):
    print _1, _2, _3, _4, _5
    code_dict = dict(zip(range(1, 6), [_1, _2, _3, _4, _5]))
    answ = np.array(map(lambda x: code_dict[x], clust_labels+1))
    print 'accuracy: ', np.mean(answ == y_train)

1 2 3 4 5
accuracy:  0.1674285366002316
1 2 3 5 4
accuracy:  0.133540561955263
1 2 4 3 5
accuracy:  0.1353202901200707
1 2 4 5 3
accuracy:  0.14072042420917902
1 2 5 3 4
accuracy:  0.12193575912720181
1 2 5 4 3
accuracy:  0.16122386786127874
1 3 2 4 5
accuracy:  0.1895166697141464
1 3 2 5 4
accuracy:  0.15562869506917779
1 3 4 2 5
accuracy:  0.14356067532150912
1 3 4 5 2
accuracy:  0.1735478759066252
1 3 5 2 4
accuracy:  0.13017614432864022
1 3 5 4 2
accuracy:  0.19405131955872493
1 4 2 3 5
accuracy:  0.20236484427378557
1 4 2 5 3
accuracy:  0.2077649783628939
1 4 3 2 5
accuracy:  0.1885170963613092
1 4 3 5 2
accuracy:  0.2185042969464253
1 4 5 2 3
accuracy:  0.1823124276223563
1 4 5 3 2
accuracy:  0.2068994941183641
1 5 2 3 4
accuracy:  0.16163832510513806
1 5 2 4 3
accuracy:  0.20092643383921496
1 5 3 2 4
accuracy:  0.14779057719266167
1 5 3 4 2
accuracy:  0.21166575242274638
1 5 4 2 3
accuracy:  0.15497043944657768
1 5 4 3 2
accuracy:  0.1795575059425855
2 1 3 4 5
accuracy:  0.16132

Смотрим глазками.

Самое большое accuracy

In [ ]:
5 4 2 3 1
accuracy:  0.30391905893825805

Чему равнялось бы предсказание, если бы мы рандомно ставили метку?

0.2. Так что лучше, рандом. ура.